### ISSUE TITLE
Add git subdirectory tests

### ISSUE THREAD

**Issue by PCSwingle** [biobootloader/mentat#93]
Add tests for running mentat from a subdirectory of the git repository (we might have them already but I don't think we do; would be good to check first!).

**Comment by granawkins** [comment]
I can do this quick but just to clarify, what's the expected behavior exactly?

e.g. in Mentat, I navigate to `mentat/mentat`, then run `mentat code_file.py`, and it runs with the top-level `mentat` as the git root. (this needs one fix to work, `code_file_manager.py` line 50)

Are you meant to also specify paths in sibling directories? e.g. `mentat code_change.py ../tests/code_change_test.py`?

**Comment by PCSwingle** [comment]
Sorry I wasn't clear! I'm pretty sure it works as expected right now (I could be wrong); if you run it from within a subdirectory of a git repo, it correctly picks up the git root, and when you specify files when starting mentat it correctly picks the files relative to your cwd; all this issue is for is adding tests to make sure these things work correctly when the cwd is a subdirectory of the git repo. Hopefully that makes more sense, let me know if you have any other questions!

**Comment by granawkins** [comment]
Resolved by #96
